### ISSUE TITLE
ASSET

### ISSUE THREAD

**Issue by iandoug** [qwickly-org/QwickSteps#1]
Hi

FWIW, this is very similar to the somewhat older ASSET layout.

https://www.keyboard-design.com/letterlayout.html?layout=asset.en.ansi

Cheers, Ian

**Comment by karmakaze** [comment]
Hey, thanks for stopping by and commenting.

It certainly is similar. I ran into Asset later once I started looking for a name to call this layout. Didn't realize just how similar they ended up.

## Asset
```
Q   W  [F] (G) <J>  Y  [P] [U] (L) (;)

 A   S  (E) (T) [D]  H  (N) (I) (O) <R>

  Z   X   C   V   B   [K]  M   ,   .   /
```

## Qwickly
```
Q   W  <U> [D] (F) (J) [L] [P] [Y] (;)

 A   S  (E) (T)  G   H  (N) (I) (O) <R>

  Z   X   C   V   B   [K]  M   ,   .   /


Legend
    same as QWERTY
( ) same finger as QWERTY
[ ] same hand as QWERTY
< > other hand than QWERTY
```

- both only swap one pair of keys between hands: `R` and `J` vs `U`
- both keep the same number of keys unchanged from QWERTY
- both keep the same number of keys on the same finger as QWERTY
- bottom two rows are the same except for `D` vs `G`

After using the Qwickly layout for a while I started to notice when I was reaching for the `B` key when a closer place was taken with the less frequently used `K`. I think a similar thing would be noticed with Asset.

At the expense of switching another pair of keys between hands, I shuffled `B`, `K`, and `J` to make [Qwickly (Mod B)](https://github.com/qwickly-org/Qwicker#qwickly-mod-b). That was followed up with more changes in the **Qwicker** layout--I'm using the KFLY version.

**Comment by karmakaze** [comment]
keyboard-design.com is a cool site too. So much to explore in this world.
